test:
  imports:
    - group_publication_aggregator
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wpk-nist-gov/group-publication-aggregator
  summary: Routines to aggregate group publications
  description: |
    Routines to aggregate group publications
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
